[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tmdb_sdk"
version = "0.1.0"
description = "A Python SDK for TMDB API(homework)"
authors = [{name = "Nikolay Yanev", email = "nikolay.yanev56@gmail.com"}]
dependencies = [
    "requests>=2.28.0"
]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["tmdb_sdk*"]